### ISSUE TITLE
構造を教えて下さい

### ISSUE THREAD

**Issue by r-kurose** [asmsuechan/rowma#1]
やりたいことはなんとなく理解できるのですが、構造（アーキテクチャー）を図で示してもらえないでしょうか。
ハードウェアやソフトウェアがどこでどう動いて、それらがどういう関係性を持っているのかが理解できません。

ROS で作られたシステムが複数あってそれをつなぐものなのか、
それとも ROS で作られたシステムを Web UI から監視・操作できるものなのか、
といった基本的なところから理解が進みません。

**Comment by asmsuechan** [comment]
@r-kurose 
アーキテクチャはこのようになっています。

![image](https://user-images.githubusercontent.com/11307908/70147503-b2213a80-16e7-11ea-8641-d140a8f078f9.png)

まずロボット管理者は管理用ROSノード([rowma_ros](https://github.com/asmsuechan/rowma_ros))をロボット側で実行し割り当てられたUUIDを確認しておく必要があります。そしてロボット管理者はそのロボットを操作したい時にクライアント(現在はWebページ)からサーバーに接続し、管理対象のロボットのUUIDを選択して`roslaunch`等のコマンドを送信します。これを受け取ったサーバーは指定されたロボットに処理命令を送ります。

提供しているサーバーを使えばロボット管理者は管理用ROSノードを実行するだけでよい事になります。

---

> ROS で作られたシステムが複数あってそれをつなぐものなのか

ROSパッケージ同士での通信をブリッジすることはこのシステムではフォーカスしていません。ただ、その機能も面白そうなので実装を検討してみます。

> ROS で作られたシステムを Web UI から監視・操作できるものなのか

その認識で合っています。ただ、Web UIはこのシステム本体には含まれておらず、このシステムのSDKを使用した実装の1つとして簡単なWeb UIを作っている([rowma-sample](https://github.com/asmsuechan/rowma-sample))という形です。

**Comment by r-kurose** [comment]
ありがとうございました。理解できました。
