### ISSUE TITLE
rowma_sampleへのリンクが404エラーになる

### ISSUE THREAD

**Issue by Nobu19800** [asmsuechan/rowma#2]
README.mdに`https://github.com/asmsuechan/rowma_sample`へのリンクがありますが、これが404エラーになります。

**Comment by asmsuechan** [comment]
@Nobu19800 タイプミスです。こちら正しくは asmsuechan/rowma-sample になります。

**Comment by Nobu19800** [comment]
修正済みのようなのでCloseします。対応していただいてありがとうございます。
